import { Member } from '../../core/domain/Member';
import { Account } from '../../core/domain/Account';
import { Transaction } from '../../core/domain/Transaction';
import { AccountGroup } from '../../core/domain/AccountGroup';
import type { OtherLedger, OtherLedgerEntry } from '../../otherLedgers/domain/types';
export function now(): string { return new Date().toISOString().replace('T', ' ').slice(0, 19); }
export function rowToMember(r: Record<string, unknown>): Member { return new Member(r.id as string, r.name as string, (r.short_name as string | null) ?? undefined, (r.email as string | null) ?? undefined, (r.phone as string | null) ?? undefined, (r.avatar_url as string | null) ?? undefined, !!r.is_external, JSON.parse((r.metadata as string) ?? '{}') as Record<string, unknown>, r.created_at as string, r.updated_at as string, (r.deleted_at as string | null) ?? undefined); }
export function rowToAccount(r: Record<string, unknown>): Account { return new Account(r.id as string, (r.member_id as string | null) ?? undefined, r.name as string, r.type as Account['type'], r.balance as number, r.currency as string, (r.icon as string | null) ?? undefined, (r.color as string | null) ?? undefined, !!r.is_active, JSON.parse((r.metadata as string) ?? '{}') as Record<string, unknown>, r.created_at as string, r.updated_at as string, (r.deleted_at as string | null) ?? undefined); }
export function rowToTransaction(r: Record<string, unknown>): Transaction { return new Transaction(r.id as string, r.type as Transaction['type'], r.description as string, r.amount as number, r.member_id as string, r.date as string, (r.source_account as string | null) ?? undefined, (r.dest_account as string | null) ?? undefined, (r.debtor_id as string | null) ?? undefined, (r.loan_ref as string | null) ?? undefined, JSON.parse((r.metadata as string) ?? '{}') as Record<string, unknown>, r.created_at as string, r.updated_at as string, (r.deleted_at as string | null) ?? undefined); }
export function rowToGroup(r: Record<string, unknown>): AccountGroup { return new AccountGroup(r.id as string, r.name as string, r.sort_order as number, JSON.parse((r.metadata as string) ?? '{}') as Record<string, unknown>, (r.deleted_at as string | null) ?? undefined); }
export function rowToOtherLedger(r: Record<string, unknown>): OtherLedger { return { id: r.id as string, name: r.name as string, ownerType: r.owner_type as OtherLedger['ownerType'], ownerMemberId: (r.owner_member_id as string) ?? undefined, ownerName: (r.owner_name as string) ?? undefined, startingDate: r.starting_date as string, openingBalance: r.opening_balance as number, createdAt: r.created_at as string, updatedAt: r.updated_at as string, deletedAt: (r.deleted_at as string) ?? undefined }; }
export function rowToOtherEntry(r: Record<string, unknown>): OtherLedgerEntry { return { id: r.id as string, ledgerId: r.ledger_id as string, date: r.date as string, description: r.description as string, debit: r.debit as number, credit: r.credit as number, balance: r.balance as number, linkedTransactionId: (r.linkedTransactionId as string) ?? undefined, metadata: JSON.parse((r.metadata as string) ?? '{}'), createdAt: r.created_at as string, updatedAt: r.updated_at as string, deletedAt: (r.deleted_at as string) ?? undefined }; }
